blank_lines_lower_bound = 0
blank_lines_upper_bound = 0
format_code_in_doc_comments = true
reorder_impl_items = true
spaces_around_ranges = true
unstable_features = true
use_field_init_shorthand = true
wrap_comments = true
struct_field_align_threshold = 99
